---
- name: install mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql libs
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start and enable the services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.kommanuthala.store
    register: mysql_info
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{mysql_info}}"