---
- name: install mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_password: ExpenseApp@1
  tasks:
  - name: install mysql libs
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start and enable the services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: {{ mysql_password }}
      login_host: mysql.kommanuthala.store
    register: mysql_info
    ignore_errors: true
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{mysql_info}}"

  - name: set up root password
    ansible.builtin.command:  " mysql_secure_installation --set-root-pass {{ mysql_password }}"
    when: mysql_info.failed is true